const CARD_DEFINITIONS = [
  {
    id: "unit_001",
    name: "見習い騎士",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 1,
    attack: 1,
    hp: 2,
    rarity: "bronze",
    image: "",
    text: "能力なし。",
    keywords: [],
    abilities: {}
  },
  {
    id: "unit_002",
    name: "斧の戦士",
    type: "unit",
    cardClass: "neutral",
    tribe: "soldier",
    cost: 2,
    attack: 2,
    hp: 2,
    rarity: "bronze",
    image: "",
    text: "攻撃時：相手プレイヤーに1ダメージ。",
    keywords: [],
    abilities: { onAttack: "ping_enemy_hero_1" }
  },
  {
    id: "unit_003",
    name: "盾の兵士",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 2,
    attack: 1,
    hp: 4,
    rarity: "bronze",
    image: "",
    text: "守護。",
    keywords: ["guard"],
    abilities: {}
  },
  {
    id: "unit_004",
    name: "白銀の騎士",
    type: "unit",
    cardClass: "knight",
    tribe: "whiteKnight",
    cost: 3,
    attack: 3,
    hp: 3,
    rarity: "silver",
    image: "",
    text: "覚醒時：+1/+1を追加で得る。",
    keywords: [],
    abilities: { onAwaken: "self_extra_1_1" }
  },
  {
    id: "unit_005",
    name: "突撃兵",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 3,
    attack: 4,
    hp: 2,
    rarity: "silver",
    image: "",
    text: "突進。",
    keywords: ["rush"],
    abilities: {}
  },
  {
    id: "unit_006",
    name: "鋼の守護者",
    type: "unit",
    cardClass: "knight",
    tribe: "whiteKnight",
    cost: 4,
    attack: 2,
    hp: 5,
    rarity: "gold",
    image: "",
    text: "守護。破壊時：自分プレイヤーを2回復。",
    keywords: ["guard"],
    abilities: { onDeath: "heal_owner_2" }
  },
  {
    id: "unit_007",
    name: "戦場の指揮官",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 4,
    attack: 3,
    hp: 4,
    rarity: "gold",
    image: "",
    text: "登場時：味方ユニット1体を+1/+1。",
    keywords: [],
    abilities: { onPlay: "buff_ally_1_1" }
  },
  {
    id: "unit_008",
    name: "巨大兵",
    type: "unit",
    cardClass: "neutral",
    tribe: "soldier",
    cost: 5,
    attack: 5,
    hp: 5,
    rarity: "silver",
    image: "",
    text: "能力なし。",
    keywords: [],
    abilities: {}
  },
  {
    id: "unit_009",
    name: "疾風の槍兵",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 4,
    attack: 3,
    hp: 2,
    rarity: "gold",
    image: "",
    text: "疾走。",
    keywords: ["charge"],
    abilities: {}
  },
  {
    id: "unit_010",
    name: "火花の魔導士",
    type: "unit",
    cardClass: "mage",
    tribe: "blackMage",
    cost: 3,
    attack: 2,
    hp: 3,
    rarity: "silver",
    image: "",
    text: "登場時：相手ユニット1体に2ダメージ。",
    keywords: [],
    abilities: { onPlay: "damage_enemy_unit_2" }
  },
  {
    id: "unit_011",
    name: "魂運び",
    type: "unit",
    cardClass: "mage",
    tribe: "spirit",
    cost: 3,
    attack: 2,
    hp: 2,
    rarity: "silver",
    image: "",
    text: "破壊時：カードを1枚引く。",
    keywords: [],
    abilities: { onDeath: "draw_owner_1" }
  },
  {
    id: "unit_012",
    name: "暁の剣聖",
    type: "unit",
    cardClass: "knight",
    tribe: "whiteKnight",
    cost: 5,
    attack: 4,
    hp: 4,
    rarity: "legend",
    image: "",
    text: "覚醒時：疾走を得る。",
    keywords: [],
    abilities: { onAwaken: "gain_charge" }
  },
  {
    id: "unit_013",
    name: "白盾の従者",
    type: "unit",
    cardClass: "knight",
    tribe: "whiteKnight",
    cost: 1,
    attack: 1,
    hp: 3,
    rarity: "bronze",
    image: "",
    text: "守護。",
    keywords: ["guard"],
    abilities: {}
  },
  {
    id: "unit_014",
    name: "聖堂の癒し手",
    type: "unit",
    cardClass: "knight",
    tribe: "whiteKnight",
    cost: 2,
    attack: 1,
    hp: 3,
    rarity: "bronze",
    image: "",
    text: "登場時：自分プレイヤーを3回復。",
    keywords: [],
    abilities: { onPlay: "heal_owner_3" }
  },
  {
    id: "unit_015",
    name: "前線隊長",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 3,
    attack: 2,
    hp: 4,
    rarity: "silver",
    image: "",
    text: "登場時：味方前列ユニットすべてを+1/+1。",
    keywords: [],
    abilities: { onPlay: "buff_front_allies_1_1" }
  },
  {
    id: "unit_016",
    name: "誓約の白騎士",
    type: "unit",
    cardClass: "knight",
    tribe: "whiteKnight",
    cost: 4,
    attack: 3,
    hp: 5,
    rarity: "gold",
    image: "",
    text: "守護。覚醒時：自分プレイヤーを3回復。",
    keywords: ["guard"],
    abilities: { onAwaken: "heal_owner_3" }
  },
  {
    id: "unit_017",
    name: "衛生兵",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 2,
    attack: 2,
    hp: 2,
    rarity: "bronze",
    image: "",
    text: "破壊時：自分プレイヤーを3回復。",
    keywords: [],
    abilities: { onDeath: "heal_owner_3" }
  },
  {
    id: "unit_018",
    name: "王国の鼓舞者",
    type: "unit",
    cardClass: "knight",
    tribe: "soldier",
    cost: 3,
    attack: 2,
    hp: 3,
    rarity: "silver",
    image: "",
    text: "攻撃時：自身を+1/+0。",
    keywords: [],
    abilities: { onAttack: "buff_self_1_0" }
  },
  {
    id: "unit_019",
    name: "魔弾の使い手",
    type: "unit",
    cardClass: "mage",
    tribe: "blackMage",
    cost: 2,
    attack: 2,
    hp: 2,
    rarity: "bronze",
    image: "",
    text: "登場時：相手ユニット1体に3ダメージ。",
    keywords: [],
    abilities: { onPlay: "damage_enemy_unit_3" }
  },
  {
    id: "unit_020",
    name: "書庫の魔術師",
    type: "unit",
    cardClass: "mage",
    tribe: "blackMage",
    cost: 3,
    attack: 1,
    hp: 4,
    rarity: "silver",
    image: "",
    text: "登場時：カードを1枚引く。",
    keywords: [],
    abilities: { onPlay: "draw_owner_1" }
  },
  {
    id: "unit_021",
    name: "雷紋の導師",
    type: "unit",
    cardClass: "mage",
    tribe: "blackMage",
    cost: 4,
    attack: 3,
    hp: 3,
    rarity: "gold",
    image: "",
    text: "覚醒時：相手ユニット1体に3ダメージ。",
    keywords: [],
    abilities: { onAwaken: "damage_enemy_unit_3" }
  },
  {
    id: "unit_022",
    name: "幻獣の召喚士",
    type: "unit",
    cardClass: "mage",
    tribe: "blackMage",
    cost: 4,
    attack: 2,
    hp: 4,
    rarity: "silver",
    image: "",
    text: "登場時：1/1の兵士トークンを1体召喚。",
    keywords: [],
    abilities: { onPlay: "summon_token_1_1" }
  },
  {
    id: "unit_023",
    name: "森の斥候",
    type: "unit",
    cardClass: "neutral",
    tribe: "beast",
    cost: 1,
    attack: 2,
    hp: 1,
    rarity: "bronze",
    image: "",
    text: "能力なし。",
    keywords: [],
    abilities: {}
  },
  {
    id: "unit_024",
    name: "旅の薬師",
    type: "unit",
    cardClass: "neutral",
    tribe: "soldier",
    cost: 2,
    attack: 1,
    hp: 3,
    rarity: "bronze",
    image: "",
    text: "登場時：自分プレイヤーを3回復。",
    keywords: [],
    abilities: { onPlay: "heal_owner_3" }
  },
  {
    id: "unit_025",
    name: "老練な傭兵",
    type: "unit",
    cardClass: "neutral",
    tribe: "soldier",
    cost: 4,
    attack: 4,
    hp: 4,
    rarity: "silver",
    image: "",
    text: "能力なし。",
    keywords: [],
    abilities: {}
  },
  {
    id: "unit_026",
    name: "小型竜",
    type: "unit",
    cardClass: "neutral",
    tribe: "dragon",
    cost: 3,
    attack: 3,
    hp: 2,
    rarity: "silver",
    image: "",
    text: "疾走。",
    keywords: ["charge"],
    abilities: {}
  },
  {
    id: "token_soldier_001",
    name: "兵士トークン",
    type: "unit",
    cardClass: "token",
    tribe: "token",
    collectible: false,
    cost: 1,
    attack: 1,
    hp: 1,
    rarity: "bronze",
    image: "",
    text: "効果でのみ召喚されるトークン。",
    keywords: [],
    abilities: {}
  },
  {
    id: "spell_001",
    name: "火炎弾",
    type: "spell",
    cardClass: "mage",
    tribe: "none",
    cost: 2,
    rarity: "bronze",
    image: "",
    text: "相手ユニット1体か相手プレイヤーに2ダメージ。",
    effect: "deal_2_damage"
  },
  {
    id: "spell_002",
    name: "治癒の光",
    type: "spell",
    cardClass: "knight",
    tribe: "none",
    cost: 2,
    rarity: "bronze",
    image: "",
    text: "自分プレイヤーを3回復。",
    effect: "heal_3"
  },
  {
    id: "spell_003",
    name: "戦術補給",
    type: "spell",
    cardClass: "neutral",
    tribe: "none",
    cost: 2,
    rarity: "bronze",
    image: "",
    text: "カードを1枚引く。",
    effect: "draw_1"
  },
  {
    id: "spell_004",
    name: "力の紋章",
    type: "spell",
    cardClass: "knight",
    tribe: "none",
    cost: 1,
    rarity: "bronze",
    image: "",
    text: "味方ユニット1体を+1/+1。",
    effect: "buff_ally_1"
  },
  {
    id: "spell_005",
    name: "雷撃",
    type: "spell",
    cardClass: "mage",
    tribe: "none",
    cost: 3,
    rarity: "silver",
    image: "",
    text: "相手ユニット1体に4ダメージ。",
    effect: "deal_4_to_unit"
  },
  {
    id: "spell_006",
    name: "鼓舞",
    type: "spell",
    cardClass: "knight",
    tribe: "none",
    cost: 2,
    rarity: "silver",
    image: "",
    text: "味方ユニットすべてを+1/+0。",
    effect: "buff_all_allies_attack_1"
  },
  {
    id: "spell_007",
    name: "浄化の雨",
    type: "spell",
    cardClass: "mage",
    tribe: "none",
    cost: 4,
    rarity: "gold",
    image: "",
    text: "すべてのユニットに2ダメージ。",
    effect: "all_units_2"
  },
  {
    id: "spell_008",
    name: "聖なる祈り",
    type: "spell",
    cardClass: "knight",
    tribe: "none",
    cost: 3,
    rarity: "silver",
    image: "",
    text: "自分プレイヤーを5回復。",
    effect: "heal_5"
  },
  {
    id: "spell_009",
    name: "徴兵令",
    type: "spell",
    cardClass: "knight",
    tribe: "none",
    cost: 2,
    rarity: "silver",
    image: "",
    text: "1/1の兵士トークンを1体召喚。",
    effect: "summon_token_1_1"
  },
  {
    id: "spell_010",
    name: "前線号令",
    type: "spell",
    cardClass: "knight",
    tribe: "none",
    cost: 3,
    rarity: "gold",
    image: "",
    text: "味方前列ユニットすべてを+1/+1。",
    effect: "buff_front_allies_1_1"
  },
  {
    id: "spell_011",
    name: "魔力探求",
    type: "spell",
    cardClass: "mage",
    tribe: "none",
    cost: 3,
    rarity: "silver",
    image: "",
    text: "カードを2枚引く。",
    effect: "draw_2"
  },
  {
    id: "spell_012",
    name: "焦熱波",
    type: "spell",
    cardClass: "mage",
    tribe: "none",
    cost: 5,
    rarity: "gold",
    image: "",
    text: "相手ユニットすべてに3ダメージ。",
    effect: "enemy_all_3"
  },
  {
    id: "spell_013",
    name: "魔力の矢",
    type: "spell",
    cardClass: "mage",
    tribe: "none",
    cost: 2,
    rarity: "bronze",
    image: "",
    text: "相手ユニット1体に2ダメージ。",
    effect: "deal_2_to_unit"
  },
  {
    id: "spell_014",
    name: "旅人の知恵",
    type: "spell",
    cardClass: "neutral",
    tribe: "none",
    cost: 1,
    rarity: "bronze",
    image: "",
    text: "カードを1枚引く。",
    effect: "draw_1"
  },
  {
    id: "field_001",
    name: "訓練場",
    type: "field",
    cardClass: "knight",
    tribe: "none",
    cost: 2,
    rarity: "silver",
    image: "",
    text: "自分のターン開始時、味方ユニット1体を+1/+0。",
    effect: "field_train"
  },
  {
    id: "field_002",
    name: "癒しの泉",
    type: "field",
    cardClass: "knight",
    tribe: "none",
    cost: 3,
    rarity: "gold",
    image: "",
    text: "自分のターン開始時、自分プレイヤーを1回復。",
    effect: "field_heal"
  },
  {
    id: "field_003",
    name: "魔導研究所",
    type: "field",
    cardClass: "mage",
    tribe: "none",
    cost: 3,
    rarity: "gold",
    image: "",
    text: "自分のターン開始時、カードを1枚引く。",
    effect: "field_draw"
  },
  {
    id: "extra_001",
    name: "覚醒竜グランヴェイル",
    type: "extra_unit",
    cardClass: "neutral",
    tribe: "dragon",
    cost: 5,
    attack: 5,
    hp: 5,
    rarity: "legend",
    image: "",
    condition: "graveyard_units_5",
    text: "自分の墓地のユニットが5体以上なら召喚できる。登場時：相手ユニット1体に3ダメージ。",
    keywords: ["guard"],
    abilities: { onPlay: "damage_enemy_unit_3" }
  },
  {
    id: "extra_002",
    name: "終焉の魔弾",
    type: "extra_spell",
    cardClass: "mage",
    tribe: "none",
    cost: 4,
    rarity: "legend",
    image: "",
    condition: "low_hp_10",
    text: "自分の体力が10以下なら使用できる。相手ユニットすべてに2ダメージ。",
    effect: "enemy_all_2"
  },
  {
    id: "extra_003",
    name: "英雄覚醒",
    type: "extra_spell",
    cardClass: "knight",
    tribe: "none",
    cost: 3,
    rarity: "legend",
    image: "",
    condition: "awaken_used_2",
    text: "この試合で覚醒を2回以上使っていれば使用できる。味方ユニットすべてを+1/+1。",
    effect: "buff_all_allies_1_1"
  },
  {
    id: "extra_004",
    name: "白騎士団の号令",
    type: "extra_spell",
    cardClass: "knight",
    tribe: "none",
    cost: 4,
    rarity: "legend",
    image: "",
    condition: "awaken_used_2",
    text: "味方前列ユニットすべてを+1/+1し、1/1の兵士トークンを1体召喚。",
    effect: "knight_extra_rally"
  },
  {
    id: "extra_005",
    name: "黒魔導の大渦",
    type: "extra_spell",
    cardClass: "mage",
    tribe: "none",
    cost: 5,
    rarity: "legend",
    image: "",
    condition: "spells_cast_3",
    text: "この試合中にスペルを3回以上使用していれば使える。相手ユニットすべてに3ダメージ。",
    effect: "enemy_all_3"
  },
  {
    id: "extra_006",
    name: "古き竜の目覚め",
    type: "extra_unit",
    cardClass: "neutral",
    tribe: "dragon",
    cost: 6,
    attack: 6,
    hp: 6,
    rarity: "legend",
    image: "",
    condition: "graveyard_units_5",
    text: "登場時：相手ユニット1体に3ダメージ。",
    keywords: ["charge"],
    abilities: { onPlay: "damage_enemy_unit_3" }
  },
  {
    id: "extra_007",
    name: "魂の再編",
    type: "extra_spell",
    cardClass: "neutral",
    tribe: "none",
    cost: 3,
    rarity: "legend",
    image: "",
    condition: "graveyard_units_5",
    text: "カードを2枚引き、自分プレイヤーを5回復。",
    effect: "draw_2_heal_5"
  }
];

const FIXED_DECK_LIST = [
  ["unit_001", 3],
  ["unit_002", 2],
  ["unit_003", 3],
  ["unit_004", 2],
  ["unit_005", 2],
  ["unit_006", 2],
  ["unit_007", 2],
  ["unit_008", 2],
  ["unit_009", 1],
  ["unit_012", 1],
  ["unit_013", 2],
  ["unit_014", 2],
  ["spell_002", 1],
  ["spell_003", 1],
  ["spell_004", 1],
  ["spell_006", 1],
  ["field_001", 1],
  ["field_002", 1]
];

const MAGE_DECK_LIST = [
  ["unit_002", 2],
  ["unit_008", 2],
  ["unit_010", 3],
  ["unit_011", 3],
  ["unit_019", 3],
  ["unit_020", 2],
  ["unit_021", 2],
  ["unit_022", 2],
  ["unit_023", 2],
  ["unit_026", 1],
  ["spell_001", 3],
  ["spell_005", 2],
  ["spell_011", 2],
  ["spell_013", 1]
];

const DEFAULT_EXTRA_DECKS = {
  knight: ["extra_001", "extra_003", "extra_004", "extra_006", "extra_007"],
  mage: ["extra_001", "extra_002", "extra_005", "extra_006", "extra_007"]
};

const CPU_DECKS = {
  knight: {
    id: "knight",
    name: "ナイトCPU",
    classId: "knight",
    cards: FIXED_DECK_LIST,
    extra: DEFAULT_EXTRA_DECKS.knight
  },
  mage: {
    id: "mage",
    name: "メイジCPU",
    classId: "mage",
    cards: MAGE_DECK_LIST,
    extra: DEFAULT_EXTRA_DECKS.mage
  },
  random: {
    id: "random",
    name: "ランダムCPU",
    classId: "random",
    cards: null
  }
};

const FULL_IMAGE_BY_NAME = {
  "前線隊長": "assets/cards/ナイト/前線隊長.png",
  "戦場の指揮官": "assets/cards/ナイト/戦場の指揮官.png",
  "暁の剣聖": "assets/cards/ナイト/暁の剣聖.png",
  "王国の鼓舞者": "assets/cards/ナイト/王国の鼓舞者.png",
  "疾風の槍兵": "assets/cards/ナイト/疾風の槍兵.png",
  "白盾の従者": "assets/cards/ナイト/白盾の従者.png",
  "白銀の騎士": "assets/cards/ナイト/白銀の騎士.png",
  "盾の兵士": "assets/cards/ナイト/盾の兵士.png",
  "突撃兵": "assets/cards/ナイト/突撃兵.png",
  "聖堂の癒し手": "assets/cards/ナイト/聖堂の癒し手.png",
  "衛生兵": "assets/cards/ナイト/衛生兵.png",
  "見習い騎士": "assets/cards/ナイト/見習い騎士.png",
  "誓約の白騎士": "assets/cards/ナイト/誓約の白騎士.png",
  "鋼の守護者": "assets/cards/ナイト/鋼の守護者.png",
  "巨大兵": "assets/cards/ニュートラル/巨大兵.png",
  "斧の戦士": "assets/cards/ニュートラル/斧の戦士.png",
  "覚醒竜グランヴェイル": "assets/cards/ニュートラル/覚醒竜グランヴェイル.png",
  "幻獣の召喚士": "assets/cards/メイジ/幻獣の召喚士.png",
  "書庫の魔術師": "assets/cards/メイジ/書庫の魔術師.png",
  "火花の魔導士": "assets/cards/メイジ/火花の魔導士.png",
  "雷紋の導師": "assets/cards/メイジ/雷紋の導師.png",
  "魂運び": "assets/cards/メイジ/魂運び.png",
  "魔弾の使い手": "assets/cards/メイジ/魔弾の使い手.png"
};

Object.assign(FULL_IMAGE_BY_NAME, {
  "前線号令": "assets/cards/ナイト/前線号令.png",
  "力の紋章": "assets/cards/ナイト/力の紋章.png",
  "徴兵令": "assets/cards/ナイト/徴兵令.png",
  "治癒の光": "assets/cards/ナイト/治癒の光.png",
  "癒しの泉": "assets/cards/ナイト/癒しの泉.png",
  "聖なる祈り": "assets/cards/ナイト/聖なる祈り.png",
  "白騎士団の号令": "assets/cards/ナイト/白騎士団の号令.png",
  "英雄覚醒": "assets/cards/ナイト/英雄覚醒.png",
  "訓練場": "assets/cards/ナイト/訓練場.png",
  "鼓舞": "assets/cards/ナイト/鼓舞.png",
  "兵士トークン": "assets/cards/ニュートラル/兵士.png",
  "古き竜の目覚め": "assets/cards/ニュートラル/古き竜の目覚め.png",
  "小型竜": "assets/cards/ニュートラル/小型竜.png",
  "戦術補給": "assets/cards/ニュートラル/戦場補給.png",
  "旅の薬師": "assets/cards/ニュートラル/旅の薬師.png",
  "旅人の知恵": "assets/cards/ニュートラル/旅人の知恵.png",
  "森の斥候": "assets/cards/ニュートラル/森の斥候.png",
  "老練な傭兵": "assets/cards/ニュートラル/老練な傭兵.png",
  "火炎弾": "assets/cards/メイジ/火炎弾.png",
  "浄化の雨": "assets/cards/メイジ/浄化の雨.png",
  "焦熱波": "assets/cards/メイジ/焦熱波.png",
  "終焉の魔弾": "assets/cards/メイジ/終焉の魔弾.png",
  "黒魔導の大渦": "assets/cards/メイジ/黒魔道の大渦.png",
  "雷撃": "assets/cards/メイジ/雷撃.png",
  "魔力の矢": "assets/cards/メイジ/魔力の矢.png",
  "魔力探求": "assets/cards/メイジ/魔力探究.png",
  "魔導研究所": "assets/cards/メイジ/魔導研究所.png",
  "魂の再編": "assets/cards/ニュートラル/魂の再編.png"
});

const DEFAULT_NUMBER_LAYOUT = {
  cost: { x: 16.8, y: 10.5 },
  attack: { x: 17.0, y: 91.2 },
  hp: { x: 84.5, y: 91.2 }
};

const NUMBER_LAYOUT_BY_NAME = {
  "前線隊長": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "戦場の指揮官": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "暁の剣聖": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "王国の鼓舞者": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "疾風の槍兵": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "白盾の従者": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "白銀の騎士": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "盾の兵士": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "突撃兵": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "聖堂の癒し手": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "衛生兵": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "見習い騎士": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "誓約の白騎士": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "鋼の守護者": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "巨大兵": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "斧の戦士": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "覚醒竜グランヴェイル": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "幻獣の召喚士": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "書庫の魔術師": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "火花の魔導士": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "雷紋の導師": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "魂運び": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } },
  "魔弾の使い手": { cost: { x: 16.8, y: 10.5 }, attack: { x: 17.0, y: 91.2 }, hp: { x: 84.5, y: 91.2 } }
};

Object.keys(FULL_IMAGE_BY_NAME).forEach((name) => {
  NUMBER_LAYOUT_BY_NAME[name] ??= DEFAULT_NUMBER_LAYOUT;
});

CARD_DEFINITIONS.forEach((card) => {
  card.image ??= "";
  card.fullImage ??= FULL_IMAGE_BY_NAME[card.name] || "";
  card.numberLayout ??= NUMBER_LAYOUT_BY_NAME[card.name] || null;
  card.cardClass ??= "neutral";
  card.tribe ??= ["unit", "extra_unit"].includes(card.type) ? "soldier" : "none";
  card.collectible ??= true;
});

window.CardGameData = {
  version: "1.0",
  cards: CARD_DEFINITIONS,
  defaultNumberLayout: DEFAULT_NUMBER_LAYOUT,
  numberLayouts: NUMBER_LAYOUT_BY_NAME,
  fixedDeck: FIXED_DECK_LIST,
  extra: ["extra_001", "extra_002", "extra_003", "extra_004", "extra_005", "extra_006", "extra_007"],
  defaultExtraDecks: DEFAULT_EXTRA_DECKS,
  frameImages: {
    knight: {
      unit: "assets/cards/カード枠/ナイト_ユニット.png",
      spell: "assets/cards/カード枠/ナイト_スペル.png",
      field: "assets/cards/カード枠/ナイト_スペル.png",
      extra_unit: "assets/cards/カード枠/ナイト_ユニット_エクストラ.png",
      extra_spell: "assets/cards/カード枠/ナイト_スペル_エクストラ.png"
    },
    mage: {
      unit: "assets/cards/カード枠/メイジ_ユニット.png",
      spell: "assets/cards/カード枠/メイジ_スペル.png",
      field: "assets/cards/カード枠/メイジ_スペル.png",
      extra_unit: "assets/cards/カード枠/メイジ_ユニット_エクストラ.png",
      extra_spell: "assets/cards/カード枠/メイジ_スペル_エクストラ.png"
    },
    neutral: {
      unit: "assets/cards/カード枠/ニュートラル_ユニット.png",
      spell: "assets/cards/カード枠/ニュートラル_スペル.png",
      field: "assets/cards/カード枠/ニュートラル_スペル.png",
      extra_unit: "assets/cards/カード枠/ニュートラル_ユニット_エクストラ.png",
      extra_spell: "assets/cards/カード枠/ニュートラル_スペル_エクストラ.png"
    },
    token: {
      unit: "assets/cards/カード枠/ニュートラル_ユニット.png"
    }
  },
  classIcons: {
    knight: "assets/クラスアイコン/ナイトアイコン.png",
    mage: "assets/クラスアイコン/メイジアイコン.png"
  },
  backgrounds: {
    home: "assets/背景/ホーム画面背景.png",
    battle: "assets/背景/対戦画面背景.png"
  },
  classes: {
    knight: "ナイト",
    mage: "メイジ"
  },
  cardClasses: {
    neutral: "ニュートラル",
    knight: "ナイト",
    mage: "メイジ",
    token: "トークン"
  },
  tribes: {
    none: "なし",
    soldier: "兵士",
    whiteKnight: "白騎士",
    blackMage: "黒魔導士",
    beast: "獣",
    dragon: "竜",
    spirit: "霊魂",
    token: "トークン"
  },
  cpuDecks: CPU_DECKS,
  deckRules: {
    size: 30,
    defaultClassId: "knight",
    storageKey: "sixLaneCardBattle.playerDeck",
    rarityLimits: {
      bronze: 3,
      silver: 3,
      gold: 2,
      legend: 1
    },
    excludedTypes: ["extra_unit", "extra_spell"],
    excludedClasses: ["token"]
  },
  extraDeckRules: {
    size: 5,
    maxCopies: 1,
    allowedTypes: ["extra_unit", "extra_spell"],
    excludedClasses: ["token"]
  }
};
